<a href="https://colab.research.google.com/github/A-jha/TENSOR-FLOW-LAB/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental concept of Tensor using Tensorflow

## Agenda
- introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
- Using @tf.function (a way to speed up regular python functions)
- Using GPUs/TPUs With tensorflow
- Some Excercises 

# Introduction to Tensors

In [1]:
#import tensorflow
import tensorflow as tf

#print version of tensorflow
print("Version of Tensorflow : ",tf.__version__)

Version of Tensorflow :  2.5.0


 **tf.constant()** - To create Tensors

In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check dimensions of tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check Dimensions of vector
vector.ndim

1

In [8]:
# Create a Matrix
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Check dimention of matrix
matrix.ndim

2

In [13]:
# Create Another Matrix
another_matrix = tf.constant([[10.,8.],[8.,10.],[9.,8.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 8., 10.],
       [ 9.,  8.]], dtype=float16)>

In [14]:
# Check dimention of another matrix
another_matrix.ndim

2

In [15]:
# Create a Tensor
tensor = tf.constant([[[1,2],[3,4]],
                      [[5,6],[6,7]],
                      [[8,9],[9,10]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 6,  7]],

       [[ 8,  9],
        [ 9, 10]]], dtype=int32)>

In [16]:
# check dimensions of Tensor
tensor.ndim

3

### What we have created so far
- Scalar : a single number
- Vector : a number with direction
- Matrix : a two dimentional array of numbers
- Tensor : an n-dimensional array of numbers
  - when n = 0 then scalar / tensor
  - when n = 1 then vector / tensor
  - when n = 3 then matrix / tensor
  - when n > 3 then tensor

**tf.varible()** - To create Tensor

In [20]:
# create a tensor using tf.Variable()
# V is in uppercase
variable_tensor = tf.Variable([10, 7])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [22]:
# create a tensor using tf.constant()
constant_tensor = tf.constant([10, 7])
constant_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [24]:
# change the value of variable_tensor using simple = 
variable_tensor[0] = 12

TypeError: ignored

In [25]:
# change the value of varible using .assign object
variable_tensor[0].assign(12)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([12,  7], dtype=int32)>

In [26]:
# Now try to change constant_tensor using =
constant_tensor[0] = 12

TypeError: ignored

In [27]:
# Now try to cahnge constant_tensor using .assign object
constant_tensor[0].assign(12)

AttributeError: ignored

 **So We can conclude that :**
- **tf.constant** create a tensor with constant values
- **tf.varible** creates a tensor with varible value
  - we can change varible tensor by using **.assign** attribute

**Note :** Rarely in practice we need to decide either we use tf.constant of tf.Variable because tensorflow takes care of that

### Creating random tensor
Random tensors are tensors of some abitrary size which contains random numbers.

**What is the need of random tensor ?**

  When we pass input to nural network then in the begining nural network is going to initialize with a random tensor and during the execution it changes the value and give us the final output.

In [29]:
# Create two random function
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [30]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [33]:
# Are they equal ?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Suffle the order of element in tensor
