<a href="https://colab.research.google.com/github/A-jha/TENSOR-FLOW-LAB/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental concept of Tensor using Tensorflow

## Agenda
- introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
- Using @tf.function (a way to speed up regular python functions)
- Using GPUs/TPUs With tensorflow
- Some Excercises 

# Introduction to Tensors

In [1]:
#import tensorflow
import tensorflow as tf

#print version of tensorflow
print("Version of Tensorflow : ",tf.__version__)

Version of Tensorflow :  2.5.0


 **tf.constant()** - To create Tensors

In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check dimensions of tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check Dimensions of vector
vector.ndim

1

In [8]:
# Create a Matrix
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Check dimention of matrix
matrix.ndim

2

In [13]:
# Create Another Matrix
another_matrix = tf.constant([[10.,8.],[8.,10.],[9.,8.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 8., 10.],
       [ 9.,  8.]], dtype=float16)>

In [14]:
# Check dimention of another matrix
another_matrix.ndim

2

In [15]:
# Create a Tensor
tensor = tf.constant([[[1,2],[3,4]],
                      [[5,6],[6,7]],
                      [[8,9],[9,10]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 6,  7]],

       [[ 8,  9],
        [ 9, 10]]], dtype=int32)>

In [16]:
# check dimensions of Tensor
tensor.ndim

3

### What we have created 
- Scalar : a single number
- Vector : a number with direction
- Matrix : a two dimentional array of numbers
- Tensor : an n-dimensional array of numbers
  - when n = 0 then scalar / tensor
  - when n = 1 then vector / tensor
  - when n = 3 then matrix / tensor
  - when n > 3 then tensor

**tf.varible()** - To create Tensor