<a href="https://colab.research.google.com/github/A-jha/TENSOR-FLOW-LAB/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental concept of Tensor using Tensorflow

## Agenda
- introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
- Using @tf.function (a way to speed up regular python functions)
- Using GPUs/TPUs With tensorflow
- Some Excercises 

# 1. Introduction to Tensors

In [ ]:
#import tensorflow
import tensorflow as tf

#print version of tensorflow
print("Version of Tensorflow : ",tf.__version__)

Version of Tensorflow :  2.5.0


 **tf.constant()** - To create Unchangable Tensors

In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check dimensions of tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check Dimensions of vector
vector.ndim

1

In [ ]:
# Create a Matrix
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check dimention of matrix
matrix.ndim

2

In [ ]:
# Create Another Matrix
another_matrix = tf.constant([[10.,8.],[8.,10.],[9.,8.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 8., 10.],
       [ 9.,  8.]], dtype=float16)>

In [ ]:
# Check dimention of another matrix
another_matrix.ndim

2

In [ ]:
# Create a Tensor
tensor = tf.constant([[[1,2],[3,4]],
                      [[5,6],[6,7]],
                      [[8,9],[9,10]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 6,  7]],

       [[ 8,  9],
        [ 9, 10]]], dtype=int32)>

In [ ]:
# check dimensions of Tensor
tensor.ndim

3

### What we have created so far
- Scalar : a single number
- Vector : a number with direction
- Matrix : a two dimentional array of numbers
- Tensor : an n-dimensional array of numbers
  - when n = 0 then scalar / tensor
  - when n = 1 then vector / tensor
  - when n = 3 then matrix / tensor
  - when n > 3 then tensor

**tf.varible()** - To create Variable Tensor

In [ ]:
# create a tensor using tf.Variable()
# V is in uppercase
variable_tensor = tf.Variable([10, 7])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# create a tensor using tf.constant()
constant_tensor = tf.constant([10, 7])
constant_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# change the value of variable_tensor using simple = 
variable_tensor[0] = 12

TypeError: ignored

In [ ]:
# change the value of varible using .assign object
variable_tensor[0].assign(12)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([12,  7], dtype=int32)>

In [ ]:
# Now try to change constant_tensor using =
constant_tensor[0] = 12

TypeError: ignored

In [ ]:
# Now try to cahnge constant_tensor using .assign object
constant_tensor[0].assign(12)

AttributeError: ignored

 **So We can conclude that :**
- **tf.constant** create a tensor with constant values
- **tf.varible** creates a tensor with varible value
  - we can change varible tensor by using **.assign** attribute

**Note :** Rarely in practice we need to decide either we use tf.constant of tf.Variable because tensorflow takes care of that

### Creating random tensor
Random tensors are tensors of some abitrary size which contains random numbers.

**What is the need of random tensor ?**

  When we pass input to neural network then in the begining neural network is going to initialize with a random tensor and during the execution it changes the value and give us the final output.

In [ ]:
# Create two random function
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Are they equal ?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Suffle the order of element in tensor


In [ ]:
# shuffle a tensor (Valuable for when you want to shuffle your data so inherent order doen't effect learning)
tensor = tf.constant([[1,2],[3,4],[4,5]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int32)>

In [ ]:
# dimention of not suffled tensor
tensor.ndim

2

In [ ]:
# shuffle the tensor as rendom rows
# passing seed as local
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
# suffle the tensor 
# passing seed as global
tf.random.set_seed(42)
tf.random.shuffle(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [4, 5],
       [1, 2]], dtype=int32)>

In [ ]:
# if we want our original tensor
tf.random.set_seed(42) # global level seed
tf.random.shuffle(tensor,seed = 42) #operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int32)>

### Other ways to create tensor

In [ ]:
# create a tensor of one
tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of zero
tf.zeros([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into Tensors
- The main difference between Numpy array and tensorflow tensor is that tensor can run on **GPU** (much faster for numerical computing)

In [ ]:
import numpy as np

In [ ]:
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,dtype=float,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.]], dtype=float32)>

# 2. Getting information from Tensor

### Tensor attributes
- Shape : The length (number of elements) of each dimensions of tensor.
  - Code : `tensor.shape`

- Rank : The number of tensor dimension.
  - A scalar has rank 0
  - A vector has rank 1
  - A matrix has rank 2
  - A tensor has rank n
    - code : `tensor.ndim`

- Axis or Dimnension : A particular dimension of tensor
  - Code : tensor[0] , tensor[ : , 1] ...

- Size : The total number of items in the tensor.
  - Code : `tf.size(tensor)`