<a href="https://colab.research.google.com/github/A-jha/TENSOR-FLOW-LAB/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental concept of Tensor using Tensorflow

## Agenda
- introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
- Using @tf.function (a way to speed up regular python functions)
- Using GPUs/TPUs With tensorflow
- Some Excercises 

# 1. Introduction to Tensors

In [1]:
#import tensorflow
import tensorflow as tf

#print version of tensorflow
print("Version of Tensorflow : ",tf.__version__)

Version of Tensorflow :  2.5.0


 **tf.constant()** - To create Unchangable Tensors

In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check dimensions of tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check Dimensions of vector
vector.ndim

1

In [6]:
# Create a Matrix
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check dimention of matrix
matrix.ndim

2

In [8]:
# Create Another Matrix
another_matrix = tf.constant([[10.,8.],[8.,10.],[9.,8.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 8., 10.],
       [ 9.,  8.]], dtype=float16)>

In [9]:
# Check dimention of another matrix
another_matrix.ndim

2

In [10]:
# Create a Tensor
tensor = tf.constant([[[1,2],[3,4]],
                      [[5,6],[6,7]],
                      [[8,9],[9,10]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 6,  7]],

       [[ 8,  9],
        [ 9, 10]]], dtype=int32)>

In [11]:
# check dimensions of Tensor
tensor.ndim

3

### What we have created so far
- Scalar : a single number
- Vector : a number with direction
- Matrix : a two dimentional array of numbers
- Tensor : an n-dimensional array of numbers
  - when n = 0 then scalar / tensor
  - when n = 1 then vector / tensor
  - when n = 3 then matrix / tensor
  - when n > 3 then tensor

**tf.varible()** - To create Variable Tensor

In [12]:
# create a tensor using tf.Variable()
# V is in uppercase
variable_tensor = tf.Variable([10, 7])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [13]:
# create a tensor using tf.constant()
constant_tensor = tf.constant([10, 7])
constant_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [15]:
# change the value of variable_tensor using simple = 
variable_tensor[0] = 12

TypeError: ignored

In [16]:
# change the value of varible using .assign object
variable_tensor[0].assign(12)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([12,  7], dtype=int32)>

In [17]:
# Now try to change constant_tensor using =
constant_tensor[0] = 12

TypeError: ignored

In [18]:
# Now try to cahnge constant_tensor using .assign object
constant_tensor[0].assign(12)

AttributeError: ignored

 **So We can conclude that :**
- **tf.constant** create a tensor with constant values
- **tf.varible** creates a tensor with varible value
  - we can change varible tensor by using **.assign** attribute

**Note :** Rarely in practice we need to decide either we use tf.constant of tf.Variable because tensorflow takes care of that

### Creating random tensor
Random tensors are tensors of some abitrary size which contains random numbers.

**What is the need of random tensor ?**

  When we pass input to neural network then in the begining neural network is going to initialize with a random tensor and during the execution it changes the value and give us the final output.

In [19]:
# Create two random function
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [20]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [21]:
# Are they equal ?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Suffle the order of element in tensor


In [22]:
# shuffle a tensor (Valuable for when you want to shuffle your data so inherent order doen't effect learning)
tensor = tf.constant([[1,2],[3,4],[4,5]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int32)>

In [23]:
# dimention of not suffled tensor
tensor.ndim

2

In [24]:
# shuffle the tensor as rendom rows
# passing seed as local
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [3, 4],
       [1, 2]], dtype=int32)>

In [25]:
# suffle the tensor 
# passing seed as global
tf.random.set_seed(42)
tf.random.shuffle(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [4, 5],
       [1, 2]], dtype=int32)>

In [26]:
# if we want our original tensor
tf.random.set_seed(42) # global level seed
tf.random.shuffle(tensor,seed = 42) #operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int32)>

### Other ways to create tensor

In [27]:
# create a tensor of one
tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
# create a tensor of zero
tf.zeros([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into Tensors
- The main difference between Numpy array and tensorflow tensor is that tensor can run on **GPU** (much faster for numerical computing)

In [29]:
import numpy as np

In [30]:
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [31]:
A = tf.constant(numpy_A,dtype=float,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.]], dtype=float32)>

# 2. Getting information from Tensor

| attributes | Meaning | Code |
|------------|---------|------|
| Shape | The length (number of elements) of each dimensions of tensor.|`tensor.shape`|
|Rank | The number of tensor dimension.  <li>A scalar has rank 0</li> <li> A vector has rank 1 </li> <li>A matrix has rank 2</li> <li> A tensor has rank n</li>| `tensor.ndim`|
| Axis or Dimnension | A particular dimension of tensor | tensor[0] , tensor[ : , 1] ...|
| Size | The total number of items in the tensor.| `tf.size(tensor)`|

In [32]:
# Crrate a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [34]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
# Get various attributes of tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("No of Dimensions/Rank : ", rank_4_tensor.ndim)
print("Shape of Tensor", rank_4_tensor.shape)
print("size of tensor", tf.size(rank_4_tensor))
print("size of tensor", tf.size(rank_4_tensor).numpy())
print("Element along the 0 axis: ",rank_4_tensor.shape[0])
print("Element along last axis : ",rank_4_tensor.shape[-1])

Datatype of every element:  <dtype: 'float32'>
No of Dimensions/Rank :  4
Shape of Tensor (2, 3, 4, 5)
size of tensor tf.Tensor(120, shape=(), dtype=int32)
size of tensor 120
Element along the 0 axis:  2
Element along last axis :  5


### Indexing Tensor
- Tensors can be indexed just like Python-List

In [36]:
# get first 2 elements of each dimention
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [38]:
rank_2_tensor.ndim

2

In [39]:
# last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [40]:
# FIRST ITEM OF EACH ROW
rank_2_tensor[:1,:]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [41]:
# Add extra dimention to rank_2_tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [44]:
# or we can not write like this so ...
rank_3_tensor = rank_2_tensor(:, :, tf.newaxis)
rank_3_tensor

SyntaxError: ignored

In [45]:
# Another alternative of tf.newaxis is
# Extra dimention at the end
tf.expand_dims(rank_2_tensor,axis=-1)#-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [46]:
# Extra dimension in the start
tf.expand_dims(rank_2_tensor,axis =0)# expand 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

## Manipulating Tensors
**Basic Operations**

`+` , `-` , `*` , `/`

In [47]:
# we can add values to the tensor using addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [48]:
# add 10 to each element
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [49]:
# subtract 10
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [50]:
# multiply 10
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [51]:
# divide 10
tensor /10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [52]:
# in above operation we are not changing original tensor to do so
tensor = tensor/5
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

**Tensorflow built in function to do same operations**
  - **Note -** To get advantage of tensor flow use built in function as much as possible.

In [53]:
# get our original tensor
tensor = tf.multiply(tensor,5)

In [54]:
# these function are in math module of tensor flow so we can do this too
tf.math.multiply(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[50., 35.],
       [15., 20.]])>

In [55]:
# divide tensor
tf.divide(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

## Matrix Multiplication
 - In machine learning, matrix multiplication is most common tensor operations.
- [Learn more](https://www.mathsisfun.com/algebra/matrix-multiplying.html) 
- To Visual Example [visit](http://matrixmultiplication.xyz/)

To multiply an **m×n** matrix by an **n×p** matrix, the **n**s must be the same,
and the result is an **m×p** matrix.
- inner elemnet must match
 - `m * n and n * p results m * p`

In [56]:
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10.,  7.],
       [ 3.,  4.]])>

In [57]:
# mutiply the tensor with it self using * operator will return index based product of element
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[100.,  49.],
       [  9.,  16.]])>

In [58]:
# We can use python `@` operator to multiply matrix in a proper manner
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[121.,  98.],
       [ 42.,  37.]])>

In [59]:
# Or we can use inbuilt tf.lialg.matmul
tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[121.,  98.],
       [ 42.,  37.]])>

In [60]:
# or we can directly write and this is alias
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[121.,  98.],
       [ 42.,  37.]])>

In [61]:
# create some tensors
t1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(t1)
print("dimension of t1 : ",t1.ndim)

t2 = tf.constant([[1,2],[3,4],[4,5]])
print(t2)
print("dimention/rank of t2 : ", t2.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
dimension of t1 :  2
tf.Tensor(
[[1 2]
 [3 4]
 [4 5]], shape=(3, 2), dtype=int32)
dimention/rank of t2 :  2


In [62]:
# as per our multiplication condition we can multiply these matrix m * n and n * p results m * p
# for t1 m = 3 and n =3
# for t2 n = 3 and p =2
# result has m = 3 and n = 2
tf.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[19, 25],
       [43, 58],
       [67, 91]], dtype=int32)>

In [63]:
# create another matrix 
t3 = tf.constant([[1,2],[2,3]])
print(t3)
t3.ndim

tf.Tensor(
[[1 2]
 [2 3]], shape=(2, 2), dtype=int32)


2

In [64]:
# here is it possible to multiply t1 and t3 let's look 
# for t1 m = 3 and n = 3
# for t3 n = 2 and p = 2 
# here n != n hence multiplication is not possible
tf.matmul(t1,t3)

InvalidArgumentError: ignored

In [65]:
# is it possible to multiply t2 and t3 let's look
# for t2 m = 3 and n =2
# for t3 n = 2 and p = 2
# here n == n hence we can multiply t2 and t3 
# hence ouptut is of shape m = 3 and p = 2
tf.linalg.matmul(t2,t3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  8],
       [11, 18],
       [14, 23]], dtype=int32)>

In [66]:
# Lets have one more example
a = tf.constant([[1,2,3],[4,5,6]])
print(a)

b = tf.constant([[7,8,9],[10,11,12]])
print(b)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [67]:
# multiply a and b
tf.linalg.matmul(a,b)

InvalidArgumentError: ignored

In [ ]:
# reshape b such that inner element matches
tf.matmul(a,tf.reshape(b,shape=(3,2)))


In [68]:
# reshape a such that inner element matches
tf.matmul(tf.reshape(a,shape=(3,2)),b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [69]:
# we can transpose to get the above result
print("original a : ",a)
print("Transposed a : ",tf.transpose(a))
tf.linalg.matmul(tf.transpose(a) , b)

original a :  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Transposed a :  tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]], dtype=int32)>

**dot Product**
Matrix Multiplication is also refered as dot product.
- We can perform matrix multiplication using 
  - `tf.linalg.matmul()`
  - `tf.tensordot()`

In [70]:
# perform dot product on x and y (requires x or y to be transposed)
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

y = tf.constant([[7, 8, 9], [10, 11, 12]])
print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [71]:
tf.tensordot(x, y,axes=1) # through an error that inner element does not matches

InvalidArgumentError: ignored

In [ ]:
# so the correct way is to transpose one of them
tf.tensordot(tf.transpose(x), y,axes=1)

Generally, when performing matrix multiplication on two tensors and one axes doesn't lineup, then we transpose (rather than reshaping )the tensor to get satify the matrix multiplication rules..

## Changing Datatype of the tensor 
**tf.cast(tensor, tf.dtype)**

In [ ]:
# Create a tensor with default datatype
B = tf.constant([1.7,3.5])
B, B.dtype

In [ ]:
C = tf.constant([3,6])
C.dtype

### Mixed precision 
Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory.

Today, most models use the float32 dtype, which takes 32 bits of memory. However, there are two lower-precision dtypes, float16 and bfloat16, each which take 16 bits of memory instead. Modern accelerators can run operations faster in the 16-bit dtypes, as they have specialized hardware to run 16-bit computations and 16-bit dtypes can be read from memory faster.

**Reduce Precision :** Lowering the base of datatype is called reduced precision.

In [72]:
# change float32 to float16 
D = tf.cast(B,dtype=tf.float16)
D, D.dtype

NameError: ignored

In [ ]:
# Change int32 to float32
E = tf.cast(C,dtype=tf.float32)
E, E.dtype 

## Aggregating Tensors
- **Aggregation :** 
  - a cluster of things that have come or been brought together.
  - (on the internet) the collection of related items of content so that they can be displayed or linked to.

- Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

- Some Aggregation Forms 
  - tf.abs() - to get absolute value.
  - tf.reduce_max() - to get Maximum value from tensor.
  - tf.reduce_min() - to get minimum value from tensor.
  - tf.reduce_mean() - to get mean of tensor.
  - tf.reduce_sum() - o get sum of element of tensor

In [74]:
# Create a  tensor
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [73]:
# get absolute value
tf.abs(D)

NameError: ignored

In [75]:
# create a tensor
tensor = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [76]:
# max of tensor
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [77]:
# minimum of tensor
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [78]:
# minimum element in axis=0
tf.reduce_min(tensor,axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [79]:
# maximum in axis =1
tf.reduce_max(tensor,axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [80]:
# mean of tensor
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [81]:
# sum of tensor
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [82]:
# size of tensor
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [83]:
# calculate mean manually
tf.reduce_sum(tensor)/ tf.size(tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=5.0>

### Varience and Stadard deviation of tensor

**Waht is Varience?**

The average of the squared differences from the Mean.

**Waht is Standard Deviation?**

the Standard Deviation is just the square root of Variance

[Must Visit once](https://www.mathsisfun.com/data/standard-deviation.html)


In [84]:
# create a random tensor
random_tensor = tf.constant(np.random.randint(0,100,size=50))
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41,  5,  1, 12, 80, 93,  3, 77,  6, 47, 55, 95, 18, 85, 99, 51, 41,
       22, 48, 58, 87, 28, 22, 42, 78, 25, 23, 95, 34, 53, 65, 42, 75, 95,
       57, 43, 67,  2, 94, 79, 34, 29, 79, 65, 96, 41, 57, 76, 34, 21])>

In [85]:
tf.constant(np.std(random_tensor))

<tf.Tensor: shape=(), dtype=float64, numpy=29.128165064075013>

In [86]:
tf.constant(np.ceil(np.var(random_tensor)))

<tf.Tensor: shape=(), dtype=float64, numpy=849.0>

In [87]:
#to use tensorflow mw=ethod we need to import tensorflow_probablity 
import tensorflow_probability as tfp

In [88]:
# calculate varience
tfp.stats.variance(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=848>

In [89]:
# calculate std deviation using tf.math.reduce_std gives error that input must be real or complex
tf.math.reduce_std(random_tensor)

TypeError: ignored

In [91]:
#lets convert out tensor to float32 using cast
tf.math.reduce_std(tf.cast(random_tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.128166>

In [92]:
# calculate standard deviation using tfp.stats.stddev
tfp.stats.stddev(random_tensor)

InvalidArgumentError: ignored

In [93]:
#try after casting
tfp.stats.stddev(tf.cast(random_tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.128166>